### ISSUE TITLE
Deprecation for authentication via URL query parameters

### ISSUE THREAD

**Issue by kolappannathan** [managedkaos/keyword-releaser#1]
After using this action I recieved the following email email from the GitHub

> Hi @kolappannathan,
> 
> On June 17th, 2020 at 08:41 (UTC) your personal access token (GitHub Action: Auto Release) using HTTPie/2.1.0 was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/xxxxxxxx/releases
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by managedkaos** [comment]
Thanks for the heads up!  I'll take a look at updating the code.
